//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "album_track")]
pub struct Model {
    pub album_id: i32,
    pub track_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    // #[sea_orm(
    //     belongs_to = "super::albums::Entity",
    //     from = "Column::AlbumId",
    //     to = "super::albums::Column::AlbumId",
    //     on_update = "NoAction",
    //     on_delete = "NoAction"
    // )]
    Albums,
    // #[sea_orm(
    //     belongs_to = "super::tracks::Entity",
    //     from = "Column::TrackId",
    //     to = "super::tracks::Column::TrackId",
    //     on_update = "NoAction",
    //     on_delete = "NoAction"
    // )]
    Tracks,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Albums => Entity::belongs_to(super::albums::Entity).from(Column::album_id
            ).to(super::albums::Column::AlbumId).into(),
            Self::Tracks => Entity::belongs_to(super::tracks::Entity).from(Column::track_id).to(super::tracks::Column::TrackId).into(),
        }
    }
}

// impl Related<super::albums::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::Albums.def()
//     }
// }

// impl Related<super::tracks::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::Tracks.def()
//     }
// }

impl ActiveModelBehavior for ActiveModel {}
