//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "album_picture")]
pub struct Model {
    pub album_id: i32,
    pub picture_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    Albums,
    Pictures,
}
impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Albums => Entity::belongs_to(super::albums::Entity).from(Column::album_id
            ).to(super::albums::Column::AlbumId).into(),
            Self::Pictures => Entity::belongs_to(super::pictures::Entity).from(Column::picture_id).to(super::pictures::Column::PictureId).into(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
