//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "album_track")]
pub struct Model {
    pub album_id: i32,
    pub track_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    Albums,
    Tracks,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Albums => Entity::belongs_to(super::albums::Entity).from(Column::album_id
            ).to(super::albums::Column::AlbumId).into(),
            Self::Tracks => Entity::belongs_to(super::tracks::Entity).from(Column::track_id).to(super::tracks::Column::TrackId).into(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
