//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "band_user")]
pub struct Model {
    pub band_id: i32,
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    Bands,
    Users,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Bands => Entity::belongs_to(super::bands::Entity).from(Column::band_id
            ).to(super::albums::Column::BandId).into(),
            Self::Users => Entity::belongs_to(super::users::Entity).from(Column::user_id).to(super::labels::Column::UserId).into(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
