//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "band_label")]
pub struct Model {
    pub band_id: i32,
    pub label_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    Bands,
    Labels,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Bands => Entity::belongs_to(super::bands::Entity).from(Column::band_id
            ).to(super::albums::Column::BandId).into(),
            Self::Labels => Entity::belongs_to(super::labels::Entity).from(Column::label_id).to(super::labels::Column::LabelId).into(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
