//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub mod prelude;

pub mod album_picture;
pub mod album_track;
pub mod albums;
pub mod band_label;
pub mod band_picture;
pub mod band_user;
pub mod bands;
pub mod genres;
pub mod labels;
pub mod pictures;
pub mod playlist_track;
pub mod playlists;
pub mod tracks;
pub mod user_label;
pub mod user_picture;
pub mod users;
