//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pictures")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub picture_id: i32,
    pub path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_picture::Entity")]
    AlbumPicture,
    #[sea_orm(has_many = "super::band_picture::Entity")]
    BandPicture,
    #[sea_orm(has_many = "super::user_picture::Entity")]
    UserPicture,
}

impl Related<super::album_picture::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumPicture.def()
    }
}

impl Related<super::band_picture::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandPicture.def()
    }
}

impl Related<super::user_picture::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPicture.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
