//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_label")]
pub struct Model {
    pub user_id: i32,
    pub label_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    Labels,
    Users,
}


impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity).from(Column::user_id
            ).to(super::users::Column::UserId).into(),
            Self::Labels => Entity::belongs_to(super::labels::Entity).from(Column::label_id).to(super::labels::Column::LabelId).into(),
        }
    }
}


impl ActiveModelBehavior for ActiveModel {}
