//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: i32,
    pub first_name: String,
    pub last_name: String,
    pub username: String,
    pub email: String,
    pub user_type: String,
    pub online: bool,
    pub deleted_at: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::albums::Entity")]
    Albums,
    #[sea_orm(has_many = "super::band_user::Entity")]
    BandUser,
    #[sea_orm(has_many = "super::playlists::Entity")]
    Playlists,
    #[sea_orm(has_many = "super::user_label::Entity")]
    UserLabel,
    #[sea_orm(has_many = "super::user_picture::Entity")]
    UserPicture,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Albums.def()
    }
}

impl Related<super::band_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BandUser.def()
    }
}

impl Related<super::playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Playlists.def()
    }
}

impl Related<super::user_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLabel.def()
    }
}

impl Related<super::user_picture::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPicture.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
