//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_picture")]
pub struct Model {
    pub user_id: i32,
    pub picture_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    // #[sea_orm(
    //     belongs_to = "super::pictures::Entity",
    //     from = "Column::PictureId",
    //     to = "super::pictures::Column::PictureId",
    //     on_update = "NoAction",
    //     on_delete = "NoAction"
    // )]
    Pictures,
    // #[sea_orm(
    //     belongs_to = "super::users::Entity",
    //     from = "Column::UserId",
    //     to = "super::users::Column::UserId",
    //     on_update = "NoAction",
    //     on_delete = "NoAction"
    // )]
    Users,
}

// impl Related<super::pictures::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::Pictures.def()
//     }
// }

// impl Related<super::users::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::Users.def()
//     }
// }

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity).from(Column::user_id
            ).to(super::users::Column::UserId).into(),
            Self::Pictures => Entity::belongs_to(super::pictures::Entity).from(Column::picture_id).to(super::pictures::Column::PictureId).into(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
